### ISSUE TITLE
Crash when cloning attribute

### ISSUE THREAD

**Issue by JeanLucPons** [tango-controls/pogo#54]
When I try to paste an attribute, I get the following NullPointerException.
Pogo 9.6.19.

`
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.tango.pogo.pogo_gui.tools.OAWutils.cloneAttribute(OAWutils.java:846)
	at org.tango.pogo.pogo_gui.AttributeDialog.cloneAttribute(AttributeDialog.java:1825)
	at org.tango.pogo.pogo_gui.ClassTree.pasteItem(ClassTree.java:760)
	at org.tango.pogo.pogo_gui.ClassTree.access$3800(ClassTree.java:58)
	at org.tango.pogo.pogo_gui.ClassTree$ClassTreePopupMenu.menuActionPerformed(ClassTree.java:2594)
	at org.tango.pogo.pogo_gui.ClassTree$ClassTreePopupMenu.access$3400(ClassTree.java:2395)
	at org.tango.pogo.pogo_gui.ClassTree$ClassTreePopupMenu$1.actionPerformed(ClassTree.java:2413)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.tango.pogo.pogo_gui.tools.OAWutils.cloneAttribute(OAWutils.java:846)
	at org.tango.pogo.pogo_gui.AttributeDialog.cloneAttribute(AttributeDialog.java:1825)
	at org.tango.pogo.pogo_gui.ClassTree.pasteItem(ClassTree.java:760)
	at org.tango.pogo.pogo_gui.ClassTree.access$3800(ClassTree.java:58)
	at org.tango.pogo.pogo_gui.ClassTree$ClassTreePopupMenu.menuActionPerformed(ClassTree.java:2594)
	at org.tango.pogo.pogo_gui.ClassTree$ClassTreePopupMenu.access$3400(ClassTree.java:2395)
	at org.tango.pogo.pogo_gui.ClassTree$ClassTreePopupMenu$1.actionPerformed(ClassTree.java:2413)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.Abs
`

**Comment by Pascal-Verdier** [comment]
I cannot reproduce the issue.
