### ISSUE TITLE
Pogo does not work with java 11 or higher

### ISSUE THREAD

**Issue by Pascal-Verdier** [tango-controls/pogo#93]
Hi
Pogo does not work with java 11 or higher.
I tried to modified the dependencies but after several different changes, Maven still fails.

Any idea ?

**Comment by Ingvord** [comment]
It seems there is no straightforward solution.

As [Xtext does not support Java 11+](https://github.com/eclipse/xtext/issues/1316)

Even though if one runs mwe2Launcher on Java 8 the generated code can not be compiled under Java 11. You can try it in [this](https://github.com/tango-controls/pogo/tree/try-build-pogo-with-java-11) branch

So we can:

1) contribute into Xtext and migrate it Java 11
2) dockerize pogo to freeze it with Java 8

**Comment by Ingvord** [comment]
As @Pascal-Verdier mentioned in our email correspondence newer versions of xtext (2.17+) should support Java 11.

Unfortunately if we just upgrade xtext version to 2.21.0 mwe2Launcher (xtext generator) fails with an error on Java 11:

```
1    ERROR Mwe2Launcher       - [XtextLinkingDiagnostic: null:26 Couldn't resolve reference to JvmType 'Generator'., XtextLinkingDiagnostic: null:27 Couldn't resolve reference to JvmIdentifiableElement 'pathRtProject'., XtextLinkingDiagnostic: null:28 Couldn't resolve reference to JvmIdentifiableElement 'pathUiProject'., XtextLinkingDiagnostic: null:30 Couldn't resolve reference to JvmIdentifiableElement 'projectNameRt'., XtextLinkingDiagnostic: null:31 Couldn't resolve reference to JvmIdentifiableElement 'projectNameUi'., XtextLinkingDiagnostic: null:32 Couldn't resolve reference to JvmIdentifiableElement 'language'., XtextLinkingDiagnostic: null:33 Couldn't resolve reference to JvmIdentifiableElement 'uri'., XtextLinkingDiagnostic: null:34 Couldn't resolve reference to JvmIdentifiableElement 'fileExtensions'., XtextLinkingDiagnostic: null:37 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:37 Couldn't resolve reference to JvmType 'grammarAccess.GrammarAccessFragment'., XtextLinkingDiagnostic: null:40 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:40 Couldn't resolve reference to JvmType 'ecore.EcoreGeneratorFragment'., XtextLinkingDiagnostic: null:48 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:48 Couldn't resolve reference to JvmType 'serializer.SerializerFragment'., XtextLinkingDiagnostic: null:54 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:54 Couldn't resolve reference to JvmType 'resourceFactory.ResourceFactoryFragment'., XtextLinkingDiagnostic: null:55 Couldn't resolve reference to JvmIdentifiableElement 'fileExtensions'., XtextLinkingDiagnostic: null:59 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:59 Couldn't resolve reference to JvmType 'parser.antlr.XtextAntlrGeneratorFragment'., XtextLinkingDiagnostic: null:66 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:66 Couldn't resolve reference to JvmType 'validation.JavaValidatorFragment'., XtextLinkingDiagnostic: null:67 Couldn't resolve reference to JvmIdentifiableElement 'composedCheck'., XtextLinkingDiagnostic: null:68 Couldn't resolve reference to JvmIdentifiableElement 'composedCheck'., XtextLinkingDiagnostic: null:76 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:76 Couldn't resolve reference to JvmType 'scoping.ImportNamespacesScopingFragment'., XtextLinkingDiagnostic: null:77 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:77 Couldn't resolve reference to JvmType 'exporting.QualifiedNamesFragment'., XtextLinkingDiagnostic: null:78 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:78 Couldn't resolve reference to JvmType 'builder.BuilderIntegrationFragment'., XtextLinkingDiagnostic: null:87 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:87 Couldn't resolve reference to JvmType 'formatting.FormatterFragment'., XtextLinkingDiagnostic: null:90 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:90 Couldn't resolve reference to JvmType 'labeling.LabelProviderFragment'., XtextLinkingDiagnostic: null:93 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:93 Couldn't resolve reference to JvmType 'outline.OutlineTreeProviderFragment'., XtextLinkingDiagnostic: null:94 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:94 Couldn't resolve reference to JvmType 'outline.QuickOutlineFragment'., XtextLinkingDiagnostic: null:97 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:97 Couldn't resolve reference to JvmType 'quickfix.QuickfixProviderFragment'., XtextLinkingDiagnostic: null:100 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:100 Couldn't resolve reference to JvmType 'contentAssist.JavaBasedContentAssistFragment'., XtextLinkingDiagnostic: null:103 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:103 Couldn't resolve reference to JvmType 'parser.antlr.XtextAntlrUiGeneratorFragment'., XtextLinkingDiagnostic: null:115 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:115 Couldn't resolve reference to JvmType 'types.TypesGeneratorFragment'., XtextLinkingDiagnostic: null:118 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:118 Couldn't resolve reference to JvmType 'xbase.XbaseGeneratorFragment'., XtextLinkingDiagnostic: null:121 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:121 Couldn't resolve reference to JvmType 'templates.CodetemplatesGeneratorFragment'., XtextLinkingDiagnostic: null:124 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:124 Couldn't resolve reference to JvmType 'refactoring.RefactorElementNameFragment'., XtextLinkingDiagnostic: null:127 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:127 Couldn't resolve reference to JvmType 'compare.CompareFragment'., XtextLinkingDiagnostic: null:128 Couldn't resolve reference to JvmIdentifiableElement 'fileExtensions'.]
java.lang.IllegalStateException: [XtextLinkingDiagnostic: null:26 Couldn't resolve reference to JvmType 'Generator'., XtextLinkingDiagnostic: null:27 Couldn't resolve reference to JvmIdentifiableElement 'pathRtProject'., XtextLinkingDiagnostic: null:28 Couldn't resolve reference to JvmIdentifiableElement 'pathUiProject'., XtextLinkingDiagnostic: null:30 Couldn't resolve reference to JvmIdentifiableElement 'projectNameRt'., XtextLinkingDiagnostic: null:31 Couldn't resolve reference to JvmIdentifiableElement 'projectNameUi'., XtextLinkingDiagnostic: null:32 Couldn't resolve reference to JvmIdentifiableElement 'language'., XtextLinkingDiagnostic: null:33 Couldn't resolve reference to JvmIdentifiableElement 'uri'., XtextLinkingDiagnostic: null:34 Couldn't resolve reference to JvmIdentifiableElement 'fileExtensions'., XtextLinkingDiagnostic: null:37 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:37 Couldn't resolve reference to JvmType 'grammarAccess.GrammarAccessFragment'., XtextLinkingDiagnostic: null:40 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:40 Couldn't resolve reference to JvmType 'ecore.EcoreGeneratorFragment'., XtextLinkingDiagnostic: null:48 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:48 Couldn't resolve reference to JvmType 'serializer.SerializerFragment'., XtextLinkingDiagnostic: null:54 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:54 Couldn't resolve reference to JvmType 'resourceFactory.ResourceFactoryFragment'., XtextLinkingDiagnostic: null:55 Couldn't resolve reference to JvmIdentifiableElement 'fileExtensions'., XtextLinkingDiagnostic: null:59 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:59 Couldn't resolve reference to JvmType 'parser.antlr.XtextAntlrGeneratorFragment'., XtextLinkingDiagnostic: null:66 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:66 Couldn't resolve reference to JvmType 'validation.JavaValidatorFragment'., XtextLinkingDiagnostic: null:67 Couldn't resolve reference to JvmIdentifiableElement 'composedCheck'., XtextLinkingDiagnostic: null:68 Couldn't resolve reference to JvmIdentifiableElement 'composedCheck'., XtextLinkingDiagnostic: null:76 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:76 Couldn't resolve reference to JvmType 'scoping.ImportNamespacesScopingFragment'., XtextLinkingDiagnostic: null:77 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:77 Couldn't resolve reference to JvmType 'exporting.QualifiedNamesFragment'., XtextLinkingDiagnostic: null:78 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:78 Couldn't resolve reference to JvmType 'builder.BuilderIntegrationFragment'., XtextLinkingDiagnostic: null:87 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:87 Couldn't resolve reference to JvmType 'formatting.FormatterFragment'., XtextLinkingDiagnostic: null:90 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:90 Couldn't resolve reference to JvmType 'labeling.LabelProviderFragment'., XtextLinkingDiagnostic: null:93 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:93 Couldn't resolve reference to JvmType 'outline.OutlineTreeProviderFragment'., XtextLinkingDiagnostic: null:94 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:94 Couldn't resolve reference to JvmType 'outline.QuickOutlineFragment'., XtextLinkingDiagnostic: null:97 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:97 Couldn't resolve reference to JvmType 'quickfix.QuickfixProviderFragment'., XtextLinkingDiagnostic: null:100 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:100 Couldn't resolve reference to JvmType 'contentAssist.JavaBasedContentAssistFragment'., XtextLinkingDiagnostic: null:103 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:103 Couldn't resolve reference to JvmType 'parser.antlr.XtextAntlrUiGeneratorFragment'., XtextLinkingDiagnostic: null:115 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:115 Couldn't resolve reference to JvmType 'types.TypesGeneratorFragment'., XtextLinkingDiagnostic: null:118 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:118 Couldn't resolve reference to JvmType 'xbase.XbaseGeneratorFragment'., XtextLinkingDiagnostic: null:121 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:121 Couldn't resolve reference to JvmType 'templates.CodetemplatesGeneratorFragment'., XtextLinkingDiagnostic: null:124 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:124 Couldn't resolve reference to JvmType 'refactoring.RefactorElementNameFragment'., XtextLinkingDiagnostic: null:127 Couldn't resolve reference to JvmIdentifiableElement 'fragment'., XtextLinkingDiagnostic: null:127 Couldn't resolve reference to JvmType 'compare.CompareFragment'., XtextLinkingDiagnostic: null:128 Couldn't resolve reference to JvmIdentifiableElement 'fileExtensions'.]
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:89)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:63)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:53)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:79)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:37)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Ingvord** [comment]
Might be related to https://github.com/xtext/maven-xtext-example/issues/48

**Comment by dlacoste-esrf** [comment]
just submitted a pull request (#98).
The problem was that we are using the xtext.generator but the dependency was on the xtext.xtext.generator.
Note that the later is the new standard, and the one we are using is deprecated, to be removed next release (https://www.eclipse.org/Xtext/releasenotes.html). We should consider moving to the new xtext.xtext.generator.

I also added corba as a dependency as it was missing. I think it was built in java before the 11 release actually, so this was to be expected.

**Comment by Pascal-Verdier** [comment]
The latest Pogo jar file **(9.7.0)** is now compatible and compiled with **java 11**.
The **java 8** copatibility has been lost.
The latest **java 8** release is  **9.6.31**
